### PR TITLE
Move fcc-spack to main repo

### PR DESCRIPTION
**Pull request by JavierCVilla**
For a while all the Spack related activity has been develop on my personal fork, however it should really be part of the main FCC repo.

### CODE REVIEW

**Comment by clementhelsens** [comment]
Could you also rename the package as we discussed last week not to be confused ?

**Comment by JavierCVilla** [comment]
@clementhelsens  Yes, but I would like to merge this first. After that we can request to convert the repo in a standalone repository (currently it is a fork from Joschka's repo) and finally change the name.

**Comment by clementhelsens** [comment]
ok, then I'll merge and we can follow up, but BTW, will you include CI for spack as well?

**Comment by JavierCVilla** [comment]
> @clementhelsens will you include CI for spack as well?

I would say no, the CI for this repo are basically our nightly jobs building the stack.

**Comment by clementhelsens** [comment]
ok, then I will merge

**Pull request merged**
